### ISSUE TITLE
Cannot close and send keylogs.

### ISSUE THREAD

**Issue by ghost** [xp4xbox/Puffader#44]
Hi,

I got error when I use py2exe to compile so I use pyInstaller instead without any problem.

My problem is:
When I run the exe file, it launches and starts sending screen shot every 120 seconds as default. But I do not receive any keylog even if I reduced 1000 chars to 200. No matter how many times I tried it didn't work out.

Second issue is to close Puffader with key combination of ctrl+right shift+left shift+h
I tried many times but it keeps sending screenshots.

What might be the problem?

**Comment by tehseensagar** [comment]
dear share your initial config , try to reduce it to 50 instead of 200.

Regards

**Comment by ghost** [comment]
Dear @tehseensagar 

I already set Gmail as mentioned so I can receive screenshots via email. I just cannot receive keylogs on time.

And key combination to close Puffader does not work for me.

Regards

**Comment by ghost** [comment]
OK, I understand what happens:

When I first launched my exe file, intCharPerSend was set to 1000.
Then I used the key combination to close Puffader and assumed it closed.
I change intCharPerSend to 200, compiled and run the program again. Tried typing over 200 letters and when I did not receive keylogs, I assumed it doesn't work but I have just received an e-mail with 2000+ chars.

My issue remains as closing the program.

**Comment by xp4xbox** [comment]
Try latest commit @corefinding for the program not stopping.

**Comment by xp4xbox** [comment]
I am guessing the issue is resolved.

**Comment by netm4li** [comment]
@xp4xbox sorry for my late reply due to business travel for four days.

I downloaded the Puffader again and compiled it via pyInstaller with the settings below:

`blnFTP = "False"  # if using ftp set this to True and configure the options below`
`strFtpServer = ""`
`intFtpPort = 21`
`strFtpUser = ""`
`strFtpPass = ""`
`strFtpRemotePath = "/"`

`intCharPerSend = 200  # set num of chars before send log/store`

`blnUseTime = "True"  # if you prefer to use a timer to send/save logs, set this to True`
`intTimePerSend = 300  # set how often to send/save logs in seconds`

`blnStoreLocal = "False"  # True to save logs/screens locally`
`strLogFile = "c:/temp/test.txt"  # set non-protected path to text file eg. c:/temp/test.txt`

`blnScrShot = "False"  # set to True for capturing screenshots`
`strScrDir = ""  # set non-protected dir for scrshot location if storing locally. eg c:/temp`
`intScrTime = 600  # set time for taking screen in seconds`

`blnLogClick = "True"  # for logging window clicks`
`blnAddToStartup = "False"`

`blnLogClipboard = "False"`
`blnMelt = "True"`

ctrl + rshift + lshift + h key combination still doesn't work. I tried this keys in the following forms:

On desktop;

- Pushed in combination: ctrl + rshift + lshift + h
- ctrl + lshift + rshift + h
- Tried to push them seperately in delays:
- ctrl, then rshift, then lshift then h key

None of those are working. Do you think it might be related to compiling with pyInstaller instead of py2exe?

**Comment by ghost** [comment]
@xp4xbox sorry for my late reply due to business travel for four days.

I downloaded the Puffader again and compiled it via pyInstaller with the settings below:

`blnFTP = "False"  # if using ftp set this to True and configure the options below`
`strFtpServer = ""`
`intFtpPort = 21`
`strFtpUser = ""`
`strFtpPass = ""`
`strFtpRemotePath = "/"`

`intCharPerSend = 200  # set num of chars before send log/store`

`blnUseTime = "True"  # if you prefer to use a timer to send/save logs, set this to True`
`intTimePerSend = 300  # set how often to send/save logs in seconds`

`blnStoreLocal = "False"  # True to save logs/screens locally`
`strLogFile = "c:/temp/test.txt"  # set non-protected path to text file eg. c:/temp/test.txt`

`blnScrShot = "False"  # set to True for capturing screenshots`
`strScrDir = ""  # set non-protected dir for scrshot location if storing locally. eg c:/temp`
`intScrTime = 600  # set time for taking screen in seconds`

`blnLogClick = "True"  # for logging window clicks`
`blnAddToStartup = "False"`

`blnLogClipboard = "False"`
`blnMelt = "True"`

ctrl + rshift + lshift + h key combination still doesn't work. I tried this keys in the following forms:

On desktop;

- Pushed in combination: ctrl + rshift + lshift + h
- ctrl + lshift + rshift + h
- Tried to push them seperately in delays:
- ctrl, then rshift, then lshift then h key

None of those are working. Do you think it might be related to compiling with pyInstaller instead of py2exe?

**Comment by xp4xbox** [comment]
Maybe, try running without compiling. I am using those settings with no problem.

**Comment by ghost** [comment]
@xp4xbox I tried it just by running Puffader.py and still not working.

Is there anything I can try?

**Comment by tehseensagar** [comment]
First of all I would suggest you to have a look on these variable settings as per below

intCharPerSend = 100 # set num of chars before send log/store

blnUseTime = "False" # if you prefer to use a timer to send/save logs, set this to True
intTimePerSend = 60 # set how often to send/save logs in seconds
strLogFile = ""

And also let us know either you are trying to send logs via email or not.

try to rebuild the config using above settings , I'm assuming you are using gmail method.

pyinstaller  --noconsole  --onefile Puffader.py

Regards

**Comment by xp4xbox** [comment]
I will keep this open for 1 more week.
